//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IhaleProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ihale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ihale()
        {
            this.Offer = new HashSet<Offer>();
        }
    
        public int IhaleId { get; set; }
        public string IhaleName { get; set; }
        public string IhaleImage { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> WinnerSupplierId { get; set; }
        public Nullable<System.DateTime> IhaleLastTime { get; set; }
        public string IhaleAdetCins { get; set; }
        public Nullable<double> IhaleAdet { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Offer> Offer { get; set; }
    }
}
